export default {
  SIGN_IN: '/signin',
  SIGN_UP: '/signup',
  MAIN: '/main',
  DICTIONARY: '/dictionary',
  SPEAK_IT: '/speak-it',
  ENGLISH_PUZZLE: '/english-puzzle',
  SAVANNA: '/savanna',
  AUDIO_CALL: '/audio-call',
  SPRINT: '/sprint',
  OWN_GAME: '/own-game',
  STATISTIC: '/statistic',
  SETTINGS: '/settings',
  PROMO: '/promo',
  ABOUT_US: '/about-us',
  WORD_CARD: '/wordcard',
};
