const MSEC_PER_HOUR = 3600000;
const REPEAT_INTERVAL_HOURS = 1;
const COEFFICIENT = 0.5;
const WORD_REPEAT_INTERVAL = REPEAT_INTERVAL_HOURS * MSEC_PER_HOUR * COEFFICIENT;

export default WORD_REPEAT_INTERVAL;
