export const SET_TOKEN = 'SIGN_IN/SET_TOKEN';
export const REMOVE_TOKEN = 'SIGN_IN/REMOVE_TOKEN';
export const SIGN_IN_RENDER = 'SIGN_IN/SIGN_IN_RENDER';
export const SET_ALERT_MESSAGE = 'SIGN_IN/SET_ALERT_MESSAGE';

export const GET_NAVBAR_STATE = 'NAVBAR/GET_STATE';
export const SET_NAVBAR_STATE = 'NAVBAR/SET_STATE';
