export const SET_USER_DATA = 'SIGN_IN/SET_USER_DATA';
export const REMOVE_USER_DATA = 'SIGN_IN/REMOVE_TOKEN';
export const SIGN_IN_RENDER = 'SIGN_IN/SIGN_IN_RENDER';
export const SET_ALERT_MESSAGE = 'SIGN_IN/SET_ALERT_MESSAGE';

// settings
export const APPLY_SETTINGS = 'APPLY_SETTINGS';
export const INIT_SETTINGS = 'INIT_SETTINGS';

// modalWindow
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';

// progress
export const DIFFERENT_CARDS_COUNTER_PLUS_ONE = 'DIFFERENT_CARDS_COUNTER_PLUS_ONE';
export const REWRITE_DATE_OF_RECEIPT_OF_WORDS = 'REWRITE_DATE_OF_RECEIPT_OF_WORDS';
export const REDUCE_LEFT_NEW_WORDS_TODAY = 'REDUCE_LEFT_NEW_WORDS_TODAY';
export const REDUCE_LEFT_REPEAT_WORDS_TODAY = 'REDUCE_LEFT_REPEAT_WORDS_TODAY';
export const RESET_PROGRESS = 'RESET_PROGRESS';
export const QUEUE_NEW_WORDS = 'QUEUE_NEW_WORDS';
export const QUEUE_REPEAT_WORDS = 'QUEUE_REPEAT_WORDS';

export const BUTTON_ACTIVITY_SWITCH = 'SIGN_IN/BUTTON_ACTIVITY_SWITCH';
